// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.mjs";
import * as Zora$1 from "zora";
import * as Js_dict from "@rescript/std/lib/es6/js_dict.js";
import * as Belt_Option from "@rescript/std/lib/es6/belt_Option.js";
import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";
import * as Garter_Json from "../../../src/Garter_Json.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (function (t) {
          t.equal(lhs, rhs, name);
          return Zora.done(undefined);
        }));
  
}

Zora$1.test("[Json] stringifyExn", (function (t) {
        t.test("object", (function (t) {
                t.equal(Garter_Json.stringifyExn({
                          x: 0
                        }), "{\"x\":0}", "");
                return Zora.done(undefined);
              }));
        t.test("undefined", (function (t) {
                t.equal(Garter_Json.stringifyExn(undefined), undefined, "");
                return Zora.done(undefined);
              }));
        
      }));

Zora$1.test("[Json] stringify", (function (t) {
        t.test("object", (function (t) {
                t.equal(Garter_Json.stringify({
                          x: 0
                        }), "{\"x\":0}", "");
                return Zora.done(undefined);
              }));
        t.test("undefined", (function (t) {
                t.equal(Garter_Json.stringify(undefined), undefined, "");
                return Zora.done(undefined);
              }));
        
      }));

Zora$1.test("[Json] parse", (function (t) {
        t.test("object", (function (t) {
                t.equal(Belt_Option.flatMap(Garter_Json.stringify({
                              x: 0
                            }), Garter_Json.parse), Caml_option.some(Js_dict.fromArray([[
                                "x",
                                0.0
                              ]])), "");
                return Zora.done(undefined);
              }));
        t.test("undefined", (function (t) {
                t.equal(Garter_Json.parse(undefined), undefined, "");
                return Zora.done(undefined);
              }));
        
      }));

function roundtrip(json) {
  return Belt_Option.flatMap(Garter_Json.stringify(json), Garter_Json.parse);
}

Zora$1.test("[Json] roundtrip", (function (t) {
        t.test("json", (function (t) {
                var json = Js_dict.fromArray([[
                        "x",
                        0.0
                      ]]);
                t.equal(Belt_Option.flatMap(Garter_Json.stringify(json), Garter_Json.parse), Caml_option.some(json), "");
                return Zora.done(undefined);
              }));
        
      }));

export {
  testEqual ,
  roundtrip ,
  
}
/*  Not a pure module */
