// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.mjs";
import * as Zora$1 from "zora";
import * as Garter_Object from "../../../src/Garter_Object.mjs";

function testEqual(t, name, lhs, rhs) {
  t.test(name, (function (t) {
          t.equal(lhs, rhs, name);
          return Zora.done(undefined);
        }));
  
}

Zora$1.test("fromKV", (function (t) {
        return testEqual(t, "1", Garter_Object.fromKV("a", 1), {
                    a: 1
                  });
      }));

export {
  testEqual ,
  
}
/*  Not a pure module */
