// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.mjs";
import * as Garter_Object from "../../src/Garter_Object.mjs";

function testEqual(name, lhs, rhs) {
  return Jest.test(name, (function (param) {
                return Jest.Expect.toEqual(rhs, Jest.Expect.expect(lhs));
              }));
}

Jest.describe("fromKV", (function (param) {
        return testEqual("1", Garter_Object.fromKV("a", 1), {
                    a: 1
                  });
      }));

export {
  testEqual ,
  
}
/*  Not a pure module */
