// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.mjs";

function testEqual(name, lhs, rhs) {
  return Jest.test(name, (function (param) {
                return Jest.Expect.toEqual(rhs, Jest.Expect.expect(lhs));
              }));
}

Jest.describe("pad", (function (param) {
        testEqual("padEnd", "foo  ", "foo".padEnd(5));
        testEqual("padEndWith", "foo..", "foo".padEnd(5, "."));
        testEqual("padStart", "  foo", "foo".padStart(5));
        return testEqual("padStartWith", "..foo", "foo".padStart(5, "."));
      }));

Jest.describe("trim", (function (param) {
        testEqual("trimEnd", "  foo", "  foo  ".trimEnd());
        return testEqual("trimStart", "foo  ", "  foo  ".trimStart());
      }));

export {
  testEqual ,
  
}
/*  Not a pure module */
