// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";

function identity(a) {
  return a;
}

function complement(f, x) {
  return !Curry._1(f, x);
}

function constantly(a, param) {
  return a;
}

export {
  identity ,
  complement ,
  constantly ,
  
}
/* No side effect */
