// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int64 from "@rescript/std/lib/es6/int64.js";
import * as Belt_Id from "@rescript/std/lib/es6/belt_Id.js";
import * as Caml_obj from "@rescript/std/lib/es6/caml_obj.js";

function cmp(a, b) {
  return a.localeCompare(b) | 0;
}

var StringComparable = Belt_Id.MakeComparableU({
      cmp: cmp
    });

function cmp$1(a, b) {
  return a - b | 0;
}

var IntComparable = Belt_Id.MakeComparableU({
      cmp: cmp$1
    });

var cmp$2 = Int64.compare;

var Int64Comparable = Belt_Id.MakeComparableU({
      cmp: cmp$2
    });

var cmp$3 = Caml_obj.compare;

var FloatComparable = Belt_Id.MakeComparableU({
      cmp: cmp$3
    });

export {
  StringComparable ,
  IntComparable ,
  Int64Comparable ,
  FloatComparable ,
}
/* StringComparable Not a pure module */
