// Generated by ReScript, PLEASE EDIT WITH CARE


function identity(a) {
  return a;
}

function complement(f, x) {
  return !f(x);
}

function constantly(a) {
  return function (param) {
    return a;
  };
}

export {
  identity ,
  complement ,
  constantly ,
}
/* No side effect */
