// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "@rescript/std/lib/es6/belt_Int.js";

function fromStringExn(s) {
  var n = Belt_Int.fromString(s);
  if (n !== undefined) {
    return n;
  }
  throw {
        RE_EXN_ID: "Failure",
        _1: "fromStringExn",
        Error: new Error()
      };
}

export {
  fromStringExn ,
}
/* No side effect */
