// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";

function stringify(x) {
  try {
    return JSON.stringify(x);
  }
  catch (exn){
    return ;
  }
}

function parse(s) {
  try {
    return Caml_option.some(JSON.parse(s));
  }
  catch (exn){
    return ;
  }
}

function stringifyExn(prim) {
  return JSON.stringify(prim);
}

export {
  stringifyExn ,
  stringify ,
  parse ,
}
/* No side effect */
