// Generated by ReScript, PLEASE EDIT WITH CARE


function stringify(x) {
  try {
    return JSON.stringify(x);
  }
  catch (exn){
    return ;
  }
}

function parse(s) {
  try {
    return JSON.parse(s);
  }
  catch (exn){
    return ;
  }
}

function stringifyExn(prim) {
  return JSON.stringify(prim);
}

export {
  stringifyExn ,
  stringify ,
  parse ,
}
/* No side effect */
