// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function apply(fa, b) {
  if (fa !== undefined && b !== undefined) {
    return Primitive_option.some(fa(Primitive_option.valFromOption(b)));
  }
}

let keepU = Belt_Option.keepU;

let keep = Belt_Option.keep;

let forEachU = Belt_Option.forEachU;

let forEach = Belt_Option.forEach;

let getExn = Belt_Option.getExn;

let getOrThrow = Belt_Option.getOrThrow;

let mapWithDefaultU = Belt_Option.mapWithDefaultU;

let mapWithDefault = Belt_Option.mapWithDefault;

let mapU = Belt_Option.mapU;

let map = Belt_Option.map;

let flatMapU = Belt_Option.flatMapU;

let flatMap = Belt_Option.flatMap;

let getWithDefault = Belt_Option.getWithDefault;

let orElse = Belt_Option.orElse;

let isSome = Belt_Option.isSome;

let isNone = Belt_Option.isNone;

let eqU = Belt_Option.eqU;

let eq = Belt_Option.eq;

let cmpU = Belt_Option.cmpU;

let cmp = Belt_Option.cmp;

let $less$star$great = apply;

export {
  keepU,
  keep,
  forEachU,
  forEach,
  getExn,
  getOrThrow,
  mapWithDefaultU,
  mapWithDefault,
  mapU,
  map,
  flatMapU,
  flatMap,
  getWithDefault,
  orElse,
  isSome,
  isNone,
  eqU,
  eq,
  cmpU,
  cmp,
  apply,
  $less$star$great,
}
/* No side effect */
