// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "@rescript/runtime/lib/es6/Js_math.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function sum_int(__x) {
  return Belt_Array.reduce(__x, 0, (s, x) => s + x | 0);
}

function sum_float(__x) {
  return Belt_Array.reduce(__x, 0, (s, x) => s + x);
}

function average_int(nums) {
  return sum_int(nums) / nums.length;
}

function average_float(nums) {
  return sum_float(nums) / nums.length;
}

function clamp_int(x, lower, upper) {
  return Math.min(Math.max(x, lower), upper);
}

function clamp_float(x, lower, upper) {
  return Math.min(Math.max(x, lower), upper);
}

let unsafe_ceil = Js_math.unsafe_ceil;

let ceil_int = Js_math.ceil_int;

let ceil = Js_math.ceil;

let unsafe_floor = Js_math.unsafe_floor;

let floor_int = Js_math.floor_int;

let floor = Js_math.floor;

let random_int = Js_math.random_int;

export {
  unsafe_ceil,
  ceil_int,
  ceil,
  unsafe_floor,
  floor_int,
  floor,
  random_int,
  sum_int,
  sum_float,
  average_int,
  average_float,
  clamp_int,
  clamp_float,
}
/* No side effect */
