name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  LANG: en_US.UTF-8

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-engines

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
